//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirVentsCadWpf.VentsCadService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameters", Namespace="http://schemas.datacontract.org/2004/07/VentsCadServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Parameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] MaterialsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirVentsCadWpf.VentsCadService.Sizes[] SizesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] Materials {
            get {
                return this.MaterialsField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialsField, value) != true)) {
                    this.MaterialsField = value;
                    this.RaisePropertyChanged("Materials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirVentsCadWpf.VentsCadService.Sizes[] Sizes {
            get {
                return this.SizesField;
            }
            set {
                if ((object.ReferenceEquals(this.SizesField, value) != true)) {
                    this.SizesField = value;
                    this.RaisePropertyChanged("Sizes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sizes", Namespace="http://schemas.datacontract.org/2004/07/VentsCadServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Sizes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LenghtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Height {
            get {
                return this.HeightField;
            }
            set {
                if ((object.ReferenceEquals(this.HeightField, value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lenght {
            get {
                return this.LenghtField;
            }
            set {
                if ((object.ReferenceEquals(this.LenghtField, value) != true)) {
                    this.LenghtField = value;
                    this.RaisePropertyChanged("Lenght");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Width {
            get {
                return this.WidthField;
            }
            set {
                if ((object.ReferenceEquals(this.WidthField, value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductPlace", Namespace="http://schemas.datacontract.org/2004/07/VentsCadServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ProductPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPdmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPdm {
            get {
                return this.IdPdmField;
            }
            set {
                if ((this.IdPdmField.Equals(value) != true)) {
                    this.IdPdmField = value;
                    this.RaisePropertyChanged("IdPdm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectId {
            get {
                return this.ProjectIdField;
            }
            set {
                if ((this.ProjectIdField.Equals(value) != true)) {
                    this.ProjectIdField = value;
                    this.RaisePropertyChanged("ProjectId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentsCadService.IVentsCadService")]
    public interface IVentsCadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/Build", ReplyAction="http://tempuri.org/IVentsCadService/BuildResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="place")]
        AirVentsCadWpf.VentsCadService.ProductPlace Build(AirVentsCadWpf.VentsCadService.Parameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/Build", ReplyAction="http://tempuri.org/IVentsCadService/BuildResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="place")]
        System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.ProductPlace> BuildAsync(AirVentsCadWpf.VentsCadService.Parameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/IsBusy", ReplyAction="http://tempuri.org/IVentsCadService/IsBusyResponse")]
        bool IsBusy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/IsBusy", ReplyAction="http://tempuri.org/IVentsCadService/IsBusyResponse")]
        System.Threading.Tasks.Task<bool> IsBusyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/BuildSp", ReplyAction="http://tempuri.org/IVentsCadService/BuildSpResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="place")]
        AirVentsCadWpf.VentsCadService.ProductPlace BuildSp(string type, string width, string height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/BuildSp", ReplyAction="http://tempuri.org/IVentsCadService/BuildSpResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="place")]
        System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.ProductPlace> BuildSpAsync(string type, string width, string height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/BuildSpigot", ReplyAction="http://tempuri.org/IVentsCadService/BuildSpigotResponse")]
        AirVentsCadWpf.VentsCadService.BuildSpigotResponse BuildSpigot(AirVentsCadWpf.VentsCadService.BuildSpigotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentsCadService/BuildSpigot", ReplyAction="http://tempuri.org/IVentsCadService/BuildSpigotResponse")]
        System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.BuildSpigotResponse> BuildSpigotAsync(AirVentsCadWpf.VentsCadService.BuildSpigotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuildSpigot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuildSpigotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string width;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string height;
        
        public BuildSpigotRequest() {
        }
        
        public BuildSpigotRequest(string type, string width, string height) {
            this.type = type;
            this.width = width;
            this.height = height;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BuildSpigotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BuildSpigotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int projectId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idPdm;
        
        public BuildSpigotResponse() {
        }
        
        public BuildSpigotResponse(int projectId, int idPdm) {
            this.projectId = projectId;
            this.idPdm = idPdm;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentsCadServiceChannel : AirVentsCadWpf.VentsCadService.IVentsCadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentsCadServiceClient : System.ServiceModel.ClientBase<AirVentsCadWpf.VentsCadService.IVentsCadService>, AirVentsCadWpf.VentsCadService.IVentsCadService {
        
        public VentsCadServiceClient() {
        }
        
        public VentsCadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentsCadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentsCadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentsCadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AirVentsCadWpf.VentsCadService.ProductPlace Build(AirVentsCadWpf.VentsCadService.Parameters parameters) {
            return base.Channel.Build(parameters);
        }
        
        public System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.ProductPlace> BuildAsync(AirVentsCadWpf.VentsCadService.Parameters parameters) {
            return base.Channel.BuildAsync(parameters);
        }
        
        public bool IsBusy() {
            return base.Channel.IsBusy();
        }
        
        public System.Threading.Tasks.Task<bool> IsBusyAsync() {
            return base.Channel.IsBusyAsync();
        }
        
        public AirVentsCadWpf.VentsCadService.ProductPlace BuildSp(string type, string width, string height) {
            return base.Channel.BuildSp(type, width, height);
        }
        
        public System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.ProductPlace> BuildSpAsync(string type, string width, string height) {
            return base.Channel.BuildSpAsync(type, width, height);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AirVentsCadWpf.VentsCadService.BuildSpigotResponse AirVentsCadWpf.VentsCadService.IVentsCadService.BuildSpigot(AirVentsCadWpf.VentsCadService.BuildSpigotRequest request) {
            return base.Channel.BuildSpigot(request);
        }
        
        public int BuildSpigot(string type, string width, string height, out int idPdm) {
            AirVentsCadWpf.VentsCadService.BuildSpigotRequest inValue = new AirVentsCadWpf.VentsCadService.BuildSpigotRequest();
            inValue.type = type;
            inValue.width = width;
            inValue.height = height;
            AirVentsCadWpf.VentsCadService.BuildSpigotResponse retVal = ((AirVentsCadWpf.VentsCadService.IVentsCadService)(this)).BuildSpigot(inValue);
            idPdm = retVal.idPdm;
            return retVal.projectId;
        }
        
        public System.Threading.Tasks.Task<AirVentsCadWpf.VentsCadService.BuildSpigotResponse> BuildSpigotAsync(AirVentsCadWpf.VentsCadService.BuildSpigotRequest request) {
            return base.Channel.BuildSpigotAsync(request);
        }
    }
}
